version: 1.0.0-release-{build}
branches:
  only:
  - master
  - release-1.0
image: Visual Studio 2019
configuration: Release
before_build:
- ps: '& .\appveyor-prebuild.ps1'
build:
  project: WinArgv.sln
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  parallel: true
  verbosity: normal
test: off
deploy:
- provider: NuGet
  api_key:
    secure: VBlOrLsxmUs+Y3Ri1c0lRxefQaose+9IqnZLat0lHzwLwILdwYQC86/BwmpGZl6j
notifications:
- provider: Email
  to:
  - petrsnd@gmail.com
  subject: WinArgv build is failing
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
