version: 1.0.0-dev-{build}
image: Visual Studio 2019
configuration: Release
before_build:
- ps: '& .\appveyor-prebuild.ps1'
build:
  project: WinArgv.sln
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  parallel: true
  verbosity: normal
deploy:
- provider: NuGet
  api_key:
    secure: Stbi8qHcFtMfe7Pv0n7PXUBWMdgibtsKm0tAtG4Dn80TZbvJ7NF1X7YaZgfKs0u5
notifications:
- provider: Email
  to:
  - petrsnd@gmail.com
  subject: WinArgv build is failing
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
